; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
globallib_dir = ./include/lib


[env:esp32dev]

platform = espressif32 @ 6.6.0  
framework = arduino

build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-Os
	-I../libraries/merlinIncludes
	;-D ARDUINO_USB_MODE=1
;	-D ARDUINO_USB_CDC_ON_BOOT=1

upload_speed =  921600
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder

lib_ldf_mode = deep+
lib_ignore = lib_deps


platform_packages =
    framework-arduinoespressif32

lib_deps = 
	;ArduinoOTA
	knolleary/PubSubClient  ;@^2.8
	PaulStoffregen/Time
	bblanchon/ArduinoJson
	https://github.com/taranais/NTPClient
	https://github.com/adafruit/Adafruit_SH110x
	https://github.com/adafruit/Adafruit-GFX-Library
    https://github.com/FluxGarage/RoboEyes

[env:wemos_d1_mini32]
extends = env:esp32dev
;upload_port = COM12

board = wemos_d1_mini32
; change microcontroller
board_build.mcu = esp32
; change MCU frequency
board_build.f_cpu = 240000000L
build_flags =
	${env:esp32dev.build_flags}
	-DMQTT_CLIENTNAME=\"esp32_opendoor_touch\"

[env:seeed_xiao_esp32c3]
extends = env:esp32dev
board = seeed_xiao_esp32c3
framework = arduino
platform = espressif32 @ 6.6.0
upload_port = COM8
upload_speed = 921600
build_flags =
	${env:esp32dev.build_flags}
	-DENABLE_TOUCH_SENSOR=0
	-DMQTT_CLIENTNAME=\"esp32_opendoor2\"


[env:esp32_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.1.13
platform = espressif32 @ 6.6.0  ; Forces the last stable v2 core or use: https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip